### ISSUE TITLE
没看明白，这是要写啥呀？😹

### ISSUE THREAD

**Issue by LiZhengXiao99** [xbwcsu/GNSS_Study#1]

**Comment by xbwcsu** [comment]
抱歉，我这边在弄github库尝试弄一下，所以测试了一下操作，我以为我的是私人库就搞了一些测试的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月10日(周三) 晚上6:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [xbwcsu/GNSS_Study] 没看明白，这是要写啥呀？😹 (Issue #1)
